name: Feature Completed Tests

on:
  push:
    branches:
      - 'feature/**'

jobs:
  feature-completed:
    name: Run tests when feature is COMPLETED
    if: |
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/heads/feature/') &&
      contains(toLower(github.event.head_commit.message), 'completed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        id: tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
          detailed_summary: true
          include_passed: true

      - name: Notify success
        if: ${{ success() }}
        run: |
          echo "All tests passed for feature branch ${{ github.ref_name }} with commit ${{ github.sha }}"

      - name: Notify failure
        if: ${{ failure() }}
        run: |
          echo "ERROR - Tests failed for feature branch ${{ github.ref_name }}; see uploaded artifacts for details"
          exit 1
